# Generated by Django 5.0.1 on 2024-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_remove_like_post_remove_like_user_post_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
