# Generated by Django 5.0.1 on 2024-02-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_post_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="modified",
            field=models.BooleanField(default=False),
        ),
    ]
